name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ coq-ci ]
  pull_request:
    branches: [ coq-ci ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: build
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # Browse URL: https://github.com/coq-community/docker-coq/wiki#supported-tags
        # to get the list of supported (coq, ocaml) versions in coqorg/coq.
        coq_version:
        #  - '8.15'
          - 'dev'
        ocaml_version:
          - '4.14.1-flambda'
      # at most 20 concurrent jobs per free account:
      # https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#usage-limits
      max-parallel: 4
      # don't cancel all in-progress jobs if one matrix job fails:
      fail-fast: false


    # Steps represent a sequence of tasks that will be executed as part of the job.
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it.
      - uses: actions/checkout@v3
      - uses: coq-community/docker-coq-action@v1
        # See https://github.com/coq-community/docker-coq-action#readme
        # for details on docker-coq-action's syntax and provided features.
#         with:
#           before_install: 'pwd; ls -al; echo $WORKDIR'
#           opam_file: 'coq-cpp2v.opam'
#           coq_version: ${{ matrix.coq_version }}
#           ocaml_version: ${{ matrix.ocaml_version }}
#         env:
#           WORKDIR: $GITHUB_WORKSPACE
        with:
          before_install: |
            startGroup "Pin dependencies"
              opam repo add -y iris-dev https://gitlab.mpi-sws.org/iris/opam.git
              opam pin add -n -y -k git coq-elpi git+https://github.com/LPCIC/coq-elpi.git#coq-master
              opam pin add -n -y -k git coq-ext-lib git+https://github.com/coq-community/coq-ext-lib#master
              opam repo
              opam list
            endGroup
          opam_file: 'coq-cpp2v.opam'
          install: |
            startGroup "Install dependencies"
              sudo apt-get update -y -q
              sudo apt-get install -y -q llvm llvm-dev clang
              opam pin add -n -y -k path coq-cpp2v-bin $WORKDIR
              opam pin add -n -y -k path $PACKAGE $WORKDIR
              opam update -y
              opam install --confirm-level=unsafe-yes -j 2 coq-cpp2v-bin --deps-only
              opam install --confirm-level=unsafe-yes -j 2 $PACKAGE --deps-only
            endGroup
          script: |
            startGroup "Build"
              opam install -y -v -j 2 coq-cpp2v-bin
              OPAMWITHTEST="1" opam install -y -v -j 2 $PACKAGE
              opam list
            endGroup
          coq_version: ${{ matrix.coq_version }}
          ocaml_version: ${{ matrix.ocaml_version }}
          export: ''
        env:
          OPAMDEBUG: '0'

